print("=" * 80)
print("FINAL RECOMMENDATION FOR YOUR CLIENT - SAN ANTONIO RENTAL CONDO")
print("=" * 80)
print()

print("CRITICAL SITUATION:")
print("• Losing $537/month ($6,444/year) in negative cash flow")
print("• Rent ($1,100) is $537 below break-even")
print("• HOA fees eating 31% of rental income")
print("• Property appreciated well but is now a cash drain")
print()

print("=" * 60)
print("CORRECTED TAX ANALYSIS (IMPORTANT)")
print("=" * 60)
print("Original Analysis had errors. Here are the CORRECT numbers:")
print()
print("If Sold Outright:")
print("• Sale Price: $230,000")
print("• Capital Gains: $150,000")
print("• Depreciation Recapture (10 years rented): ~$29,091")
print("• Total Federal Tax Bill: ~$25,409")
print("• Net After All Costs & Taxes: $157,034")
print()

print("=" * 60)
print("YOUR OPTIONS RANKED (5-YEAR OUTLOOK)")
print("=" * 60)
print()

print("🥇 OPTION 1: 1031 EXCHANGE (BEST CHOICE)")
print("-" * 40)
print("• Defer $25,409 in taxes completely")
print("• Exchange into cash-flow positive property")
print("• 5-year projected value: $310,965")
print("• Eliminates negative cash flow immediately")
print("✓ ACTION: Find replacement property with positive cash flow")
print()

print("🥈 OPTION 2: RAISE RENT TO $1,500 + KEEP")
print("-" * 40)
print("• Market rent is $1,400-$1,700")
print("• New cash flow: -$137/month (still negative)")
print("• 5-year projected value: $228,814")
print("• Reduces bleeding but doesn't stop it")
print("✓ ACTION: Immediately raise rent if keeping")
print()

print("🥉 OPTION 3: SELL AND SPLIT 50/50")
print("-" * 40)
print("• Net proceeds: $157,034 after taxes")
print("• $78,517 to stocks, $78,517 to new property")
print("• 5-year projected value: $201,147")
print("• Eliminates negative cash flow")
print("⚠️ CAUTION: Pays $25,409 in avoidable taxes")
print()

print("❌ OPTION 4: HELOC (NOT RECOMMENDED)")
print("-" * 40)
print("• Investment property HELOCs hard to get")
print("• 8.5% interest rate vs 7% stock returns")
print("• Still stuck with negative cash flow")
print("• Very few lenders in Texas offer this")
print()

print("=" * 60)
print("THE BOTTOM LINE")
print("=" * 60)
print()
print("YOUR CLIENT IS BLEEDING $6,444/YEAR")
print()
print("IMMEDIATE ACTIONS NEEDED:")
print("1. Raise rent to $1,500 TODAY (market rate)")
print("2. Start 1031 exchange process:")
print("   • List property immediately")
print("   • Hire qualified intermediary")
print("   • Identify replacement property within 45 days")
print("   • Close within 180 days")
print()
print("WHY 1031 IS BEST:")
print("✓ Preserves $25,409 in tax savings")
print("✓ Eliminates negative cash flow")
print("✓ Maintains real estate investment")
print("✓ Can buy better cash-flowing property")
print()
print("TARGET REPLACEMENT PROPERTY:")
print("• Price: $230,000-$250,000")
print("• Location: Lower cost areas (suburbs/emerging neighborhoods)")
print("• Type: Single family (lower HOA)")
print("• Cash flow: Minimum $200/month positive")
print()
print("IF CLIENT WON'T DO 1031:")
print("Then sell outright and invest proceeds.")
print("Negative cash flow + below-market rent = wealth destruction")
